

services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapipassword
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  strapi:
    image: node:18-alpine
    working_dir: /app
    restart: unless-stopped
    volumes:
      - ./:/app
    command: sh -c "npm install && npm run build && npm run develop"
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
      PORT: 1337
      DATABASE_CLIENT: mysql
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapipassword
      DATABASE_SSL: 'false'
      APP_KEYS: pHmQfOdjC7KuH8uLWN7+EA==,Z7tt2FOzTMQkYYycsplDNA==,LdSO3t0viUFjTqajpLxnRA==,mM2aGQp+1x2jhImtGsILPw==
      ADMIN_JWT_SECRET: IjBzYBJWnwPwjggBdes6lg==
      JWT_SECRET: DlIUmOuBKY9tk8qdBD6xjg==
      API_TOKEN_SALT: K3gxRmTCkqW0ZCywopkT3Q==
      STRAPI_TELEMETRY_DISABLED: 'true'
      NODE_OPTIONS: "--max-old-space-size=4096"
    ports:
      - "1337:1337"
    depends_on:
      mysql:
        condition: service_healthy

  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: "1"
    ports:
      - "8080:80"
    depends_on:
      - mysql


